# Generated by Django 5.0.6 on 2024-06-29 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_course_owner_lesson_owner_alter_course_photo_and_more"),
        ("users", "0002_alter_user_options_remove_user_username_user_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Укажите почту",
                max_length=254,
                unique=True,
                verbose_name="Почта",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payments_date",
                    models.DateTimeField(auto_now=True, verbose_name="дата оплаты"),
                ),
                (
                    "payment_sum",
                    models.PositiveIntegerField(verbose_name="сумма платежа"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "наличные"), ("card", "банковский перевод")],
                        default="card",
                        max_length=50,
                        verbose_name="способ оплаты",
                    ),
                ),
                (
                    "payment_link",
                    models.URLField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="ссылка на оплату",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="идентификатор платежа",
                    ),
                ),
                (
                    "paid_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessons.course",
                        verbose_name="оплаченный курс",
                    ),
                ),
                (
                    "paid_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessons.lesson",
                        verbose_name="оплаченный урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-payments_date"],
            },
        ),
    ]
