# Generated by Django 5.0.6 on 2024-07-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_course_owner_lesson_owner_alter_course_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание",
                null=True,
                verbose_name="Описание",
            ),
        ),
    ]
