# Generated by Django 5.0.6 on 2024-07-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0005_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на видео",
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
